### ISSUE TITLE
SoaveRedlichKwongGas on OpenFoam 11

### ISSUE THREAD

**Issue by artemis218** [ttrummler/realFOAM#2]
Hello and thank you for helpful work, 

I am working on OpenFoam Foundation 11 and attempting to implement the SoaveRedlichKwongGas EoS from the org branch. Specifically, I have compiled the SoaveRedlichKwongGas in a library and am trying link it to the solver dynamically during runtime (in the ControlDict of my simulation case), without recompiling the whole solver. In your knowledge, is this possible? And if not, how do you suggest to link the SoaveRedlichKwongGas EoS with a specific solver?

Here is an explanation of my progress so far:

OpenFoam 11 has the same structure as 10 in its original src/thermophysicalModels folder. 

I copy the whole original folder src/thermophysicalModels/specie to a ~/new_directory, I add the scripts for the SoaveRedlichKwongGas case in the ~/new_directory/specie/equationOfState. Then, I edit the ~/new_directory/specie/include/forGases.H, to include the SoaveRedlichKwongGas in the header and in the #define section. Last, I edit the ~/new_directory/specie/Make/files to generate the new lib at the ~/new_directory/specie location. The compilation is done without any evident problem and the new lib is created.

I link the new lib with my solver by adding it in the ControlDict. But when I run the case the SoaveRedlichKwongGas EoS is not recognized. By changing the name of the specie to specie1 (after modification of the corresponding names in the files within the ~/new_directory/specie/specie and the ~/new_directory/specie/Make/files), neither the specie1 is recognized by the solver.

**Comment by ttrummler** [comment]
Hello, 

sorry for my late reply. You have to recompile OpenFOAM. Maybe also something has changed in the recent updates. To be honest, I am not up to date with that. Since it is a more general OF question, you can always also ask the OF community for these kind of questions. This might be helpful for you https://doc.cfd.direct/openfoam/user-guide-v12/compiling-applications

**Comment by artemis218** [comment]
Thank you!
